name: Health Check

on:
  push:
    - testBranch

jobs:
  health_checker:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Check the deployed url
        uses: jtalk/url-health-check-action@v3
        with:
          url: https://turtle-pokedex.onrender.com
          max-attempts: 3
          retry-delay: 20s
